### ISSUE TITLE
The color swatch no longer working

### ISSUE THREAD

**Issue by TClilMouse** [lingwooc/requiredFields-magento2#1]
The color swatch no longer change the main picture under Magento 2.1.3
Getting this error message under console: TypeError: gallery is undefined

**Comment by lingwooc** [comment]
That's a shame. They must have changed more than I anticipated. I'll take a look.

**Comment by lingwooc** [comment]
@seavenger They indeed changed the handling of the gallery. I've back ported the fix to the 2.1.3 version of swatch-renderer.js. Assuming I've not made a mistake I've only changed the lookup code so the gallery should be fine again. The head revision in the master branch has the fix.
